server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**


        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**


    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true

jwt:
  secret: c2VjcmV0LW15LWtleS1zaG91bGQtYmUtMzItYnl0ZXMtYmFzZTY0IQ==


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
