server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  jwt:
    secret: c2VjcmV0LW15LWtleS1zaG91bGQtYmUtMzItYnl0ZXMtYmFzZTY0IQ==

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: auth-service-swagger
          uri: lb://auth-service
          predicates:
            - Path=/auth/v3/api-docs, /auth/swagger-ui.html, /auth/swagger-ui/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/users/v3/api-docs, /users/swagger-ui.html, /users/swagger-ui/**
          filters:
            - RewritePath=/users/(?<segment>.*), /${segment}
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
