server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  jwt:
    secret: c2VjcmV0LW15LWtleS1zaG91bGQtYmUtMzItYnl0ZXMtYmFzZTY0IQ==

  cloud:
    gateway:
      routes:

        # AUTH SERVICE MAIN
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        # AUTH SERVICE SWAGGER
        - id: auth-service-swagger
          uri: lb://auth-service
          predicates:
            - Path=/auth/swagger-ui.html, /auth/swagger-ui/**, /auth/v3/api-docs
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}
            - PreserveHostHeader

        # USER SERVICE MAIN
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /${segment}

        # USER SERVICE SWAGGER
        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/users/swagger-ui.html, /users/swagger-ui/**, /users/v3/api-docs
          filters:
            - RewritePath=/users/(?<segment>.*), /${segment}
            - PreserveHostHeader

    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


